serve:
    cookies:
        same_site_mode: Lax

urls:
    self:
        issuer: http://localhost:4444
    consent: http://localhost:3001/auth/oauth/consent
    login: http://localhost:3001/auth/oauth/login
    logout: http://localhost:3001/auth/oauth/logout

secrets:
    system:
        - youReallyNeedToChangeThis

oidc:
    subject_identifiers:
        supported_types:
            - pairwise
            - public
        pairwise:
            salt: youReallyNeedToChangeThis
