name: "Lint PR Title"

on:
    pull_request:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    pr-title:
        name: Lint PR title
        runs-on: ubuntu-latest
        steps:
            - uses: rishabhpoddar/action-semantic-pull-request
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  validateSingleCommit: true
